### ISSUE TITLE
Can't navigate to Docs, Builds, or Community in Chrome

### ISSUE THREAD

**Issue by nerdkid93** [x-tag/x-tag.github.io#9]
The website is not functional in Chrome Version 54.0.2840.99 m (64-bit).

**Comment by nerdkid93** [comment]
The following errors appears in Chrome's DevTools Console:
```
Uncaught TypeError: Cannot assign to read only property 'createdCallback' of object '#<HTMLElement>'    polydev/src/document-context/measure-custom-elements.js:60
    at HTMLDocument.wrappedRegisterElement [as registerElement]    (polydev/src/document-context/measure-custom-elements.js:60:35)
    at Object.register    (http://x-tag.github.io/js/x-tag-components.js:4349:18)
    at http://x-tag.github.io/js/x-tag-components.js:4806:8
    at http://x-tag.github.io/js/x-tag-components.js:4836:3

Uncaught TypeError: Cannot assign to read only property 'createdCallback' of object '#<HTMLElement>'    polydev/src/document-context/measure-custom-elements.js:60
    at HTMLDocument.wrappedRegisterElement [as registerElement]    (polydev/src/document-context/measure-custom-elements.js:60:35)
    at Object.register    (http://x-tag.github.io/js/x-tag-components.js:4349:18)
    at http://x-tag.github.io/js/site.js:4:6
```
It's not very encouraging if a cross-platform JS library's project page doesn't work in the latest version of Chrome.
